title: 'Tips for Las Palmas de Gran Canaria'
description: 'Maybe you want to move to Las Palmas or you want to read about what Adriaan van Rossum is doing there, either way, enjoy!'
author:
  name: 'Adriaan van Rossum'
permalink: '/:title'
timezone: 'Europe/Amsterdam'
locale: 'en'
logo: '/images/mountains.jpg'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
      type: 'pages'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      category: 'blog'

gems:
  - jemoji
