title:
  'Las Palmas Tips'
description:
  ''
author:
  name: 'Adriaan van Rossum'

defaults:
  -
    scope:
      path: ''
    values:
      layout: base
      permalink: '/:title'
  -
    scope:
      path: blog
      type: posts
    values:
      layout: posts
      permalink: '/:title'

gems:
  - jemoji
