title:
  'Las Palmas Tips'
description:
  ''
author:
  name: 'Adriaan van Rossum'

defaults:
  -
    scope:
      path: ''
    values:
      layout: base
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: posts

gems:
  - jemoji
