title:
  'Las Palmas Tips'
description:
  ''
author:
  name: 'Adriaan van Rossum'

permalink: '/:title'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
  -
    scope:
      path: 'blog'
      type: 'posts'
    values:
      layout: 'base'
      category: blog

gems:
  - jemoji
