title: 'Las Palmas Tips'
description: ''
author:
  name: 'Adriaan van Rossum'
permalink: '/:title'
timezone: 'Europe/Amsterdam'
locale: 'en'
logo: '/images/mountains.jpg'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
      type: 'pages'
  -
    scope:
      path: ''
      type: 'post'
    values:
      layout: 'post'
      category: blog

gems:
  - jemoji
