title: 'Las Palmas Tips'
description: ''
author:
  name: 'Adriaan van Rossum'
permalink: '/:title'
timezone: 'Europe/Amsterdam'
locale: 'en'

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
      type: 'pages'
  -
    scope:
      path: 'blog'
      type: 'posts'
    values:
      layout: 'base'
      category: blog

gems:
  - jemoji
