title: 'Las Palmas Tips'
description: ''
author:
  name: 'Adriaan van Rossum'
permalink: '/:title'
timezone: 'Europe/Amsterdam'
locale: 'en'
logo: '/images/mountains.jpg'

collections:
  - blog:
      output: true

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'base'
      type: 'pages'
  -
    scope:
      path: ''
      type: 'post'
    values:
      layout: 'posts'
      category: 'blog'

gems:
  - jemoji
